### ISSUE TITLE
Problem with AccountId type

### ISSUE THREAD

**Issue by bgodlin** [KILTprotocol/type-definitions#31]
Keep receiving the following error:

`failed to fetch block Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding session.setKeys:: Struct: failed on args: {"keys":"Keys","proof":"Bytes"}:: decodeU8a: failed at 0x64ddfc9ae90fce0966d382b6fe38930d… on keys: (AccountId,AccountId,AccountId,AccountId):: decodeU8a: failed at 0x0400…: AccountId:: Invalid AccountId provided, expected 32 bytes, found 2`

Seems that the same problem was discussed in https://github.com/polkadot-js/apps/issues/6172

**Comment by Diiaablo95** [comment]
Hello @bgodlin!
1. what are you trying to accomplish?
2. what SDK version are you using?
3. What chain are you trying to connect to?

**Comment by bgodlin** [comment]
1. Index KILT network using [Subquery](https://subquery.network/) to further apply business logic. As for the first goal, receive certain extrinsics and calculate the account's rewards.
2. All dependencies are in the corresponding [branch](https://github.com/soramitsu/fearless-subquery/tree/kilt).
3. Connecting [wss://peregrine.kilt.io](wss://peregrine.kilt.io) endpoint.

**Comment by bgodlin** [comment]
We are thinking more of APIs for mobile and other applications to interact with. Thus, we are trying to leverage the usage of the corresponding services such as [Subquery](https://subquery.network/) or [Subsquid](https://subsquid.io/).

**Comment by Diiaablo95** [comment]
The current blockchain runtime uses the new metadata structure, which renders type definitions obsolete. So I would suggest to not use this repo anymore, and rely solely on the runtime-injected types.

**Comment by bgodlin** [comment]
Sorry for the delay in answer - solved the issues by generating types based on a script https://github.com/polkadot-js/apps/blob/51835328db5f0eb90a9efcc7bf5510704a7ab279/packages/apps-config/src/api/spec/kilt.ts
